drop table t_pb_balao cascade constraints;
drop table t_pb_empresas cascade constraints;
drop table t_pb_convers_energia cascade constraints;
drop table t_pb_funcionarios cascade constraints;


CREATE TABLE T_PB_BALAO (
    GAS VARCHAR2 (11) NOT NULL,
    MAT_BALAO VARCHAR2 (50) NOT NULL,
    CABO_BALAO VARCHAR2 (50) NOT NULL,
    RASTREADOR_BALAO NUMBER (8) NOT NULL,
    CNPJ NUMBER (14) NOT NULL
);

ALTER TABLE T_PB_BALAO ADD CONSTRAINT PK_RASTREADOR_BALAO PRIMARY KEY (RASTREADOR_BALAO);

CREATE TABLE T_PB_EMPRESAS (
    CNPJ NUMBER (14) NOT NULL,
    NOM_EMPRE VARCHAR2 (100) NOT NULL,
    CEP_EMPRE NUMBER (10) NOT NULL,
    PLANO_EMPRE VARCHAR2 (50) NOT NULL,
    QUANTIDADE_BALAO INT DEFAULT 0
);

ALTER TABLE T_PB_EMPRESAS ADD CONSTRAINT PK_CNPJ PRIMARY KEY (CNPJ);
ALTER TABLE T_PB_BALAO ADD CONSTRAINT FK_CNPJ FOREIGN KEY (CNPJ) REFERENCES T_PB_EMPRESAS (CNPJ);

CREATE TABLE T_PB_FUNCIONARIOS (
    NOME VARCHAR2 (50) NOT NULL,
    CPF NUMBER (11) NOT NULL,
    TEL_FUNC NUMBER (15) NOT NULL,
    CARGO VARCHAR2 (50) NOT NULL
);

ALTER TABLE T_PB_FUNCIONARIOS ADD CONSTRAINT PK_CPF PRIMARY KEY (CPF);


CREATE TABLE T_PB_CONVERS_ENERGIA (
    ID_GERADOR NUMBER (9) NOT NULL,
    NUM_PAINEL_SOLAR NUMBER (10) NULL,
    GERAC_ENERG NUMBER (38) NOT NULL,
    CAPACIDADE_TOTAL NUMBER (38) NOT NULL,
    RECEPTOR_ENERG NUMBER (38) NOT NULL,
    TRANSMIS_ENERG NUMBER (38) NOT NULL
);

ALTER TABLE T_PB_CONVERS_ENERGIA ADD CONSTRAINT PK_ID_GERADOR PRIMARY KEY (ID_GERADOR);

SELECT * FROM T_PB_BALAO;
SELECT * FROM T_PB_EMPRESAS;
SELECT * FROM T_PB_FUNCIONARIOS;
SELECT * FROM T_PB_CONVERS_ENERGIA;